### ISSUE TITLE
How can you run the tools on RancherOS?

### ISSUE THREAD

**Issue by zot24** [cdrx/rancher-host-registration#1]
RancherOS doesn't have by default pip installed and it can't not be installed unless you put it in a container how will be the best way to run this tool on RancherOS systems?

**Comment by zot24** [comment]
Other issue I'm having it's how I can get the API key and secret if I don't have access to Rancher UI yet

I'm trying to automate the creation of Rancher Server a few Hosts using vagrant

**Comment by cdrx** [comment]
I can create a container with this tool in (+pip) for use on RancherOS. 

But it is only for the Rancher Agent registration, not for Rancher server. 

For the first server you must run Rancher server, and get an API key for your user. Then you would use this tool for bootstrapping other RancherOS servers that you want to connect to your existing Rancher infrastructure.

**Comment by zot24** [comment]
So you basically create a container like from `python:alpine` on the hosts (running on RancherOS) and then install this tool and run it? from where? from inside the container? or from RancherOS? how it will create the rancher/alpine container if you run it from inside the container?

**Comment by komljen** [comment]
@zot24 You can put any key and secret, it will work, because when you start rancher server from scratch it is completely open. This is how I did it with SaltStack: https://github.com/komljen/rancher-salt/blob/master/salt/docker/rancher/agent/init.sls

**Comment by imorti** [comment]
```docker run -it --name toolbox -v /:/media/root --ipc=host --net=host --pid=host ubuntu```

Then you can install tools like tcpdump, curl etc. Just restart when you need by running 
```docker start -ia toolbox```
