### ISSUE TITLE
Issue with labels (perhaps)

### ISSUE THREAD

**Issue by mbrannigan** [cdrx/rancher-host-registration#3]
I'm working on this right now, but it appears that if you pass in `--labels 'foo=bar,number=123'` the host retains the single quote:

```
'foo=bar
number=123'
```

**Comment by cdrx** [comment]
Would it be easier / cleaner to implement passing --label k=v multiple times, rather than --labels? I think click can parse multiple instances of the same argument

**Comment by mbrannigan** [comment]
Aaah.  I'll give that a shot.  I have something working, but it involves a lot of escaping.  That seems a lot cleaner.
